### ISSUE TITLE
Move `DataObjectTrait`

### ISSUE THREAD

**Issue by mecha** [Dhii/di#19]
The [`DataObjectTrait`] doesn't belong in this repo. Ideally, it should be moved to an `*-abstract` package, such as [`dhii/data-object-abstract`]

[`DataObjectTrait`]: https://github.com/Dhii/di/blob/develop/src/DataObjectTrait.php
[`dhii/data-object-abstract`]: https://github.com/Dhii/data-object-abstract

**Comment by XedinUnknown** [comment]
It aggregates traits from two different packages, `dhii/data-object-abstract` and [`dhii/container-helper-base`][], for the purposes of convenience and clarity in building the DI implementation. I don't think there is going to be a more appropriate package for this any time soon.

[`dhii/container-helper-base`]: https://github.com/Dhii/container-helper-base/tree/develop
